//Tables: Users, Comments, Paintings, Artists, Collections, Saves
//Tables that should start with data are Paintings, Artists, and Collections
//Paintings has dependencies in Artists and Collections

//Collections can be an array of Collection Titles
const collections = [
    'Slug Trails',
    'Clue',
    'The Triptych',
    'Never Say Never',
    'Recycling',
    'Cult Classics',
    'Redacted',
    'Florida, Man',
    'Birds of a Feather',
    "Noel's Fields"
]

//Artists require: name, bio, image. may contain: email, link
const artists = [
    {name: 'Cara Uhrich', bio: 'Cara Uhrich draws inspiration from nature to produce her characteristic flowing brush strokes and effortless color schemes. Working in acrylic, she experiments with a range of painting implements to stamp, roll, swipe, and sponge unique textures onto canvas. Cara is known for her compositions, which often frame recognizable subjects in disorienting ways, forcing viewers to reconsider the act of seeing itself.', image: 'https://i.imgur.com/mzrbbFT.jpg', email: 'carauhrich@gmail.com'},
    {name: 'Kirsten Brink', bio: 'Abstract painter Kirsten Brink believes in play as a foundational approach to each of her works. She is inspired by color, texture, form, and flow, and uses a range of conventional and unconventional implements to blend her distinctive color palettes. Kirsten works primarily in acrylic on canvas, leveraging metallics and an intuitive sense of color theory to produce evocative, moody compositions. Her work conjures images of otherworldly spaces, while retaining the serene rhythms of water, wind, and other natural phenomena.', image: 'https://i.imgur.com/cSjKU30.jpg', link: 'https://www.instagram.com/chaosbykay?igsh=OHI3eGJ2YTR4dmhk'},
    {name: 'Ryanne McEvoy', bio: 'Painter and collage artist Ryanne McEvoy favors high-contrast experimental compositions that recall the loud prints of 80s and 90s fashion. Her methodology could be described as improvisational; she often chooses colors and implements at random to discover what they inspire while in process. Ryanne works in acrylic on canvas, using various paint media and a combination of techniques to develop unique chemical and textural effects. One of her favorite tools is gravity itself, which she uses in combination with pouring media to add drips, spirals, marbling, and stretches to her colorful abstract works.', image: 'https://i.imgur.com/HBBO8dT.jpg'},
    {name: 'Jenny Wicks', bio: 'As a jewelry-maker and painter, Jenny Wicks aims to reintroduce balance, beauty, and symmetry into a chaotic world. During the Covid-19 quarantine, she primarily worked in acrylic on canvas to create both abstract and realistic landscapes that remind her of sunsets over Wilson Lake at her family home in Maine. Currently based in Boston, Jenny creates increasingly experimental designs that capture chaos and balance in a range of proportions. In “The Evolution of Blob,” Jenny demonstrates her keen ability to produce order in extremity and her “Nothing Good Happens After 2am” brings chaotic instability back into a peaceful, yet dark setting.', image: 'https://i.imgur.com/QpfVCiK.jpg'}
]

//Paintings require: Title, image, description, available, artistId. May contain: collectionId
const paintings = [
    {title: '144146', image: 'https://i.imgur.com/kh2WYnR.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: "90's Bus Seat", image: 'https://i.imgur.com/EpRmaJ7.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Alt Altarpiece', image: 'https://i.imgur.com/O3h9hqN.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'Altered Alt Altarpiece', image: 'https://i.imgur.com/sc69MEK.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'An Enemy', image: 'https://i.imgur.com/ntZzW4c.jpg', description: 'Watercolor on paper', available: true, artistId: 1},
    {title: 'A Time to Reflect', image: 'https://i.imgur.com/N16zyS6.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Anti Slug Trails', image: 'https://i.imgur.com/G15rXye.jpg', description: 'Acrylic on canvas vertical panel', available: false, artistId: 1, collectionId: 1},
    {title: 'Autumn', image: 'https://i.imgur.com/T3McPBX.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Banana Slug Trails', image: 'https://i.imgur.com/bSetavE.jpg', description: 'Acrylic on canvas vertical panel', available: false, artistId: 1, collectionId: 1},
    {title: 'Beads?', image: 'https://i.imgur.com/1aW271p.jpg', description: 'Acrylic on canvas vertical panel', available: false, artistId: 3, collectionId: 7},
    {title: 'Ben Wobbles', image: 'https://i.imgur.com/fkERyRg.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3, collectionId: 7},
    {title: 'Beware the Fae', image: 'https://i.imgur.com/8pS4ChK.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Blunt Force Triangle', image: 'https://i.imgur.com/sFSNhFt.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Boundless', image: 'https://i.imgur.com/iglY4HX.jpg', description: 'Acrylic on canvas horizontal panel', available: true, artistId: 2},
    {title: 'Braid', image: 'https://i.imgur.com/MVJtp6X.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Bubble Theory', image: 'https://i.imgur.com/pj3QuIn.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: 'Chameleon', image: 'https://i.imgur.com/MbHBY6k.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Celebration', image: 'https://i.imgur.com/Pelc3rd.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Change', image: 'https://i.imgur.com/I3FASLI.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: "Chiffon en l'Eau", image: 'https://i.imgur.com/Uk7BqD4.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: 'Chromatograph', image: 'https://i.imgur.com/Gnc3ipg.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'The Clash', image: 'https://i.imgur.com/wPzTauG.jpg', description: 'Acrylic on canvas', available: false, artistId: 2},
    {title: 'Cloud Cover', image: 'https://i.imgur.com/N8hUpQV.jpg', description: 'Acrylic on canvas horizontal panel', available: false, artistId: 1},
    {title: 'Cross-Section', image: 'https://i.imgur.com/BhUHfOU.jpg', description: 'Acrylic pouring paint on canvas board', available: true, artistId: 3},
    {title: 'Colonel Mustard', image: 'https://i.imgur.com/KRR49fw.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Composition Notebook', image: 'https://i.imgur.com/0dFMDrU.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: 'Covid Spike', image: 'https://i.imgur.com/KDytj59.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Crimping Iron', image: 'https://i.imgur.com/S6f9SFs.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'Cultish Behaviors', image: 'https://i.imgur.com/NzNHEhL.jpg', description: 'Acrylic on canvas', available: true, artistId: 1, collectionId: 6},
    {title: 'Deconstructed', image: 'https://i.imgur.com/5urKuMj.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Do You Remember Osmosis Jones?', image: 'https://i.imgur.com/n8JiYT3.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: 'Drag Queen', image: 'https://i.imgur.com/7GeLAhG.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Dusk on Fire', image: 'https://i.imgur.com/kNt6aBk.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Eggsuberance', image: 'https://i.imgur.com/eCdtRs0.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Enoki', image: 'https://i.imgur.com/dQOYvvx.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Eyelashes', image: 'https://i.imgur.com/QtqlRcy.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'The Evolution of Blob', image: 'https://i.imgur.com/7y6IY4L.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Fairyland', image: 'https://i.imgur.com/cEa6xCm.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Finger Print', image: 'https://i.imgur.com/loW3s82.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1},
    {title: 'Fire Elemental', image: 'https://i.imgur.com/HkFuLP5.jpg', description: 'Acrylic on canvas vertical panel', available: false, artistId: 1, collectionId: 3},
    {title: 'Fireworks', image: 'https://i.imgur.com/kLCAlwT.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'First Crack', image: 'https://i.imgur.com/ZYdASeK.jpg', description: 'Acrylic on canvas', available: false, artistId: 2, collectionId: 6},
    {title: 'Fissure', image: 'https://i.imgur.com/8ntZ8vy.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Forest', image: 'https://i.imgur.com/EV7JUfT.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Forest Floor', image: 'https://i.imgur.com/1Nn53Qe.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1},
    {title: 'F(r)og', image: 'https://i.imgur.com/YsRCy0U.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 8},
    {title: 'Froider', image: 'https://i.imgur.com/MIRSmkq.jpg', description: 'Acrylic on canvas vertical panel. A perminent piece of the Nonantum Collection', available: false, artistId: 1, collectionId: 3},
    {title: 'Foot Locker', image: 'https://i.imgur.com/3anVaRu.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Garden', image: 'https://i.imgur.com/KCjB2OW.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Geodes', image: 'https://i.imgur.com/Tys7tNG.jpg', description: 'Acrylic on canvas board. On display at the Tremont Gallery', available: false, artistId: 1},
    {title: 'Goth Girlfriend', image: 'https://i.imgur.com/DvSwE2i.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 6},
    {title: 'Growth in Chaos', image: 'https://i.imgur.com/l8OHa3m.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Grumble Volcano', image: 'https://i.imgur.com/Q7bpSHw.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'Horseshoe Crabssassination', image: 'https://i.imgur.com/Y3xrZwC.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Howl', image: 'https://i.imgur.com/6OqQObb.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Hubble Brag', image: 'https://i.imgur.com/4s77XE2.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Ilium', image: 'https://i.imgur.com/QdwZp8z.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Illuminisle', image: 'https://i.imgur.com/boryQUz.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Immolation', image: 'https://i.imgur.com/61wlKHX.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Infected Web', image: 'https://i.imgur.com/ygkNr9V.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Intertwined', image: 'https://i.imgur.com/Ut1jKiI.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Into the Spiderverse', image: 'https://i.imgur.com/wun9wpp.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: "It's Friggin' Bats!", image: 'https://i.imgur.com/utt9Gp5.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'It Comes in Waves', image: 'https://i.imgur.com/26Beg8T.jpg', description: 'Acrylic on canvas', available: false, artistId: 2},
    {title: 'Joyce', image: 'https://i.imgur.com/HCLOdQ5.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Jupiter', image: 'https://i.imgur.com/SSEhBLE.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Lil Guy', image: 'https://i.imgur.com/QIzEJSq.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Lady Luck', image: 'https://i.imgur.com/NJS19zc.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1},
    {title: 'Lazuli', image: 'https://i.imgur.com/Xr8dmve.jpg', description: 'Acrylic pouring paint on canvas', available: false, artistId: 3},
    {title: "Loki's Chaos", image: 'https://i.imgur.com/6Z6wSOB.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Looking Glass', image: 'https://i.imgur.com/Tt2QhDh.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Majesty', image: 'https://i.imgur.com/vqiSloS.jpg', description: 'Watercolor of paper', available: false, artistId: 3},
    {title: 'Manic Panic', image:'https://i.imgur.com/eWkc8fe.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Meadow', image: 'https://i.imgur.com/riS23iJ.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Meadow Grass', image: 'https://i.imgur.com/MDtDqHc.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'MeltMetal', image: 'https://i.imgur.com/MnaM3GG.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Mermaid Hair', image: 'https://i.imgur.com/toE1HG2.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Merman Beard', image: 'https://i.imgur.com/tTMxPBF.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Mermesque', image: 'https://i.imgur.com/aURrGXh.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Metamorphasis', image: 'https://i.imgur.com/dVYztxT.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Microplastics', image: 'https://i.imgur.com/349Rqoi.jpg', description: 'Acrylic on canvas', available: true, artistId: 1, collectionId: 5},
    {title: 'Moody Rainbow Fish', image: 'https://i.imgur.com/mHTi5AK.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Mr Green', image: 'https://i.imgur.com/68iDLA2.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Mrs Peacock', image: 'https://i.imgur.com/ZmVa9AH.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Mrs White', image: 'https://i.imgur.com/5LCnzJt.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Ms Scarlet', image: 'https://i.imgur.com/oTZPij8.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Nothing Good Happens After 2am', image: 'https://i.imgur.com/XTSseMg.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Oak', image: 'https://i.imgur.com/yLYBC16.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1},
    {title: 'Obsession', image: 'https://i.imgur.com/B7yNaQO.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Ocean Plastic', image: 'https://i.imgur.com/Y0aMH8s.jpg', description: 'Acrylic on canvas', available: true, artistId: 1, collectionId: 5},
    {title: 'Ogre Onion', image: 'https://i.imgur.com/hXhedJI.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Old Greg', image: 'https://i.imgur.com/fPOZH0y.jpg', description: 'Acrylic on canvas', available: true, artistId: 3, collectionId: 10},
    {title: 'Owl Belly', image: 'https://i.imgur.com/keiSLzV.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Paint Salad', image: 'https://i.imgur.com/2lKDF0D.jpg', description: 'Acrylic on canvas', available: false, artistId: 1},
    {title: 'Parrot', image: 'https://i.imgur.com/mWDykIV.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 9},
    {title: 'Peacock', image: 'https://i.imgur.com/70wGQwT.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 9},
    {title: 'Peacopy', image: 'https://i.imgur.com/ojH9qKe.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 9},
    {title: 'Percussion - More Triangle', image: 'https://i.imgur.com/Qq30dPo.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Pom Reader', image: 'https://i.imgur.com/lPZ7P7c.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 9},
    {title: 'Print Culture', image: 'https://i.imgur.com/1K5FpQ3.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Professor Plum', image: 'https://i.imgur.com/wL7HUJg.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1, collectionId: 2},
    {title: 'Quinn', image: 'https://i.imgur.com/K8EhcLA.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'The Reef', image: 'https://i.imgur.com/v8px4T1.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'Reticulum', image: 'https://i.imgur.com/N7cDq1Z.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Ripple', image: 'https://i.imgur.com/Ibg7yIM.jpg', description: 'Acrylic on canvas', available: true, artistId: 3, collectionId: 4},
    {title: 'River', image: 'https://i.imgur.com/98irByj.jpg', description: 'Acrylic on canvas board', available: true, artistId: 1},
    {title: 'Rocket Popnado', image: 'https://i.imgur.com/GplbeNm.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: 'Rolling', image: 'https://i.imgur.com/wIYANqq.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Rouge Garden', image: 'https://i.imgur.com/dbAs61V.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Rythm', image: 'https://i.imgur.com/TmMiN6I.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: 'Salad Fingers', image: 'https://i.imgur.com/eAuEAxM.jpg', description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 10},
    {title: 'Shaded Shores', image: 'https://i.imgur.com/aHoKh8y.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Shore', image: 'https://i.imgur.com/IVD5wsK.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Show Girl', image: 'https://i.imgur.com/eh5EQjA.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Smoke Stacks', image: 'https://i.imgur.com/I6BgDK3.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: 'SpaceTide', image: 'https://i.imgur.com/RyNYz0W.jpg', description: 'Acrylic on canvas board', available: true, artistId: 3},
    {title: 'Spiraling Into The Cosmos', image: 'https://i.imgur.com/lPyttwO.jpg', description: 'Acrylic on canvas', available: true, artistId: 4},
    {title: 'Spirograph', image: 'https://i.imgur.com/tFWB7E1.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Split', image: 'https://i.imgur.com/ANp3Bw1.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Spy Plane', image: 'https://i.imgur.com/2WJopa4.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Stick Bug', image: 'https://i.imgur.com/KFgQX99.jpg', description: 'Acrylic on canvas vertical panel', available: false, artistId: 1, collectionId: 3},
    {title: 'Succulent', image: 'https://i.imgur.com/HbpH6Iv.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Sun Puddles', image: 'https://i.imgur.com/jCYShQ3.jpg', description: 'Acrylic on canvas', available: false, artistId: 2},
    {title: 'Sun Rise', image: 'https://i.imgur.com/3HNvZCM.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Swamp Monster', image: 'https://i.imgur.com/KNslDcl.jpg', description: 'Acrylic on canvas', available: true, artistId: 3, collectionId: 10},
    {title: 'Swizzle', image: 'https://i.imgur.com/rckeLfr.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: 'Tadpole', image: 'https://i.imgur.com/ZJRAvDo.jpg',  description: 'Acrylic on canvas', available: false, artistId: 3, collectionId: 8},
    {title: 'Tangle', image: 'https://i.imgur.com/jRIxMrY.jpg', description: 'Acrylic on canvas', available: false, artistId: 2},
    {title: 'Tea Shore', image: 'https://i.imgur.com/9l6bKI0.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Thorax', image: 'https://i.imgur.com/mapyg5O.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Together', image: 'https://i.imgur.com/GTqZ7DM.jpg', description: 'Watercolor on canvas board', available: true, artistId: 1},
    {title: 'The Tree', image: 'https://i.imgur.com/djCx7dK.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Trellis', image: 'https://i.imgur.com/NyNBQ8V.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Unicorn Hair', image: 'https://i.imgur.com/t6de57V.jpg', description: 'Acrylic on canvas', available: true, artistId: 2},
    {title: 'Unkown Moss', image: 'https://i.imgur.com/gGDBjRU.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Uzumaki', image: 'https://i.imgur.com/s3A85XX.jpg', description: 'Acrylic on canvas', available: false, artistId: 3},
    {title: 'Vestigial', image: 'https://i.imgur.com/LHV5o3v.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: 'Vortices', image: 'https://i.imgur.com/ALWqnrs.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: 'Wake', image: 'https://i.imgur.com/jBFP41j.jpg', description: 'Acrylic on canvas', available: true, artistId: 3, collectionId: 4},
    {title: 'Wave', image: 'https://i.imgur.com/eCAubF7.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Whirlpools', image: 'https://i.imgur.com/doOws6y.jpg', description: 'Acrylic on canvas', available: false, artistId: 2},
    {title: 'White Walker', image: 'https://i.imgur.com/pjEh8X3.jpg', description: 'Acrylic on canvas', available: true, artistId: 1},
    {title: 'Wild West Thumbs', image: 'https://i.imgur.com/i7BkVHj.jpg', description: 'Acrylic pouring paint on canvas', available: true, artistId: 3},
    {title: "Your Dad's 80's Windbreaker", image: 'https://i.imgur.com/jIOLW48.jpg', description: 'Acrylic on canvas', available: true, artistId: 3},
    {title: "Your Dad's Favorite Lighthouse", image: 'https://i.imgur.com/XiWhWuC.jpg', description: 'Acrylic on canvas', available: true, artistId: 3}
]

//export data
module.exports = { collections, artists, paintings }